#!/usr/bin/env python3

from sys import argv
from pathlib import Path

def printUsage():
    print("Usage: input should be of the form:")
    print("replace path oldpattern newpattern")

def checkPaths(path, oldpattern, newpattern):
    #check absolute path
    if oldpattern in str(path):
        if path.is_dir() == False:
            #go into file and replace old with new
            with open(path, 'r') as file:
                contents = file.read()
                contents = contents.replace(oldpattern, newpattern)
            with open(path, 'w') as file:
                file.write(contents)

    #recursive paths
    if path.is_dir():
        for entry in path.iterdir():
            checkPaths(entry, oldpattern, newpattern)

if len(argv) != 4:
    printUsage()
else:
    path = argv[1]
    oldpattern = argv[2]
    newpattern = argv[3]
    
    #change string path to Path path
    path = Path(path)

    checkPaths(path, oldpattern, newpattern)

